ooyala/html5-skin

js/views/adScreen.js
js/views/endScreen.js
js/views/pauseScreen.js
js/views/startScreen.js

Firefox wasn't able to play anything because on multiple screens 'event' was referenced, but not passed to the method.

[pbw-ff-fix] making sure event is present where its called

---

js/components/controlBar.js
js/components/scrubberBar.js
js/controller.js
js/views/adScreen.js
js/views/playingScreen.js

Updates control bar hiding logic for Playing and Ad screens:
-used in full screen desktop, full/normal screen Android, normal screen iOS
-timer is set/cancelled in controller
-if control bar items touched, timer restarts
-if scrubber bar or playhead touched or moved, timer restarts

[PBW-3127] control bar hiding logic moved to controller

---

package.json

@ksunika @chibzu @aldigun @rchalooyala 
We need to upgrade our local node to v4 to work w/ this update.
Latest node version is v4.2.2

upgrade jest to work with node v4

---

scss/components/_error-screen.scss

In _error-screen.scss for .error-title adding text-align: center fixes
the issue.

[PBW-3979] Centering text of error message

---

scss/components/_discovery-screen.scss

Makes the size of discovery screen elements dynamic rather than fixed,
so they will adjust to match the view. Using a min-height/min-width to
prevent too small of an image from occurring on tiny screens.

[PBW-3857] Discovery tray in full screen is not scaling properly

---

scss/components/_closed-caption.scss

For some reason iPad Safari refused to position closed caption element correctly until I added a 1px padding.

[PBW-3992] adding 1px padding so that iPad renders CC correctly

---

js/controller.js

Publishing event to end CC at end of play. The check for ‘Safari’ was
preventing CC on replay as a result of the ending event change.

[PBW-4025] Close caption is showing on End screen

---

js/controller.js

Playhead was intentionally being set to 0,0,0 at the end of ad play.
Have instead set the values (playhead, duration, buffered) to the
current states for each

[PBW-4018] Pointer/timeline reseting after overlay

---

js/components/scrubberBar.js

Flips of the order of the check to see if we are scrubbing (seeking) and if so move icon to scrubbed position. If not, we move the icon according the the currentPlayhead. Also sets the 'scrubbingPlayheadX' (the delta on scrubbing) to 0 at the end of handlePlayheadMouseUp so that it is not constantly trying to apply the value.

[PBW-4108] Fixes Playhead icon not moving after seek.

---

js/components/scrubberBar.js

Formular for scrubber pointer used a variable that was set to 0. Using
this.props.currentPlayhead instead.

[PBW-4172] Clicking scrubber pointer reseting video to start

---

js/controller.js

OverlayAds were setting main video duration to 0 on end - visible in
pause as the scrubber moving to the end, and not easily seen during
playback because it was very quickly set back to normal, but it was
happening in both playback and pause. Change instead sets duration to
mainvideo duration at end of ad.

[PBW-4018] FIx playhead duration on overlayAd end

---

js/views/adScreen.js
scss/components/_ad-screen.scss

fixes the problem that pause animation is not visible for IMA ads because adScreen is behind the ad.

[PBW-4184] pause animation for IMA

---

js/components/closedCaptionPanel.js

Added ‘en’ as a default for the sample text if the results are blank.

[PBW-4384] No sample text if language chosen has no locality settings

---

js/controller.js

Ensure that the available languages is null when setting a new video.
We cannot do this in ‘Played’ because we cannot be sure a prior video
that has CC was fully played before a new video is set, so nulling the
list on setting an embed code, much as is done with availableBitrates.

[PBW-4390] CC button staying on replay

---

js/components/adOverlay.js
js/views/playingScreen.js
scss/components/_state-screen.scss
tests/components/adOverlay-test.js
tests/views/playingScreen-test.js

In the event listener handleOverlayClick() (adOverlay.js), adds another
condition to check if the click event target is not a button(close
button).
Furthermore in playingScreen.js within handlePlayerMouseUp() event
listener adds the same condition to check if the click was not
originated from the button(close button of overlay).

[PBW-4199] Overlay close button opening ad pages

---

js/controller.js

Bitmovin plugin adds wrapper elements around the main `video` element.
This was causing the main video element to be incorrectly set to a `div` instead of `video` and subsequently caused iOS iPad to fullscreen the `div` instead of `video`.

[PBW-4638] Fix Bitmovin iPad Fullscreen bug

---

js/controller.js

Even though overlay is being closed, the plugin object is still present
in front of the UI layer of the skin in order to fix a separate PBI
issue that was allowing users to skip past ads. This fix keeps the
object, but makes it take up no screen space, so that the UI can be
interacted with. This new fix is to avoid breaking PBI-1503.

[PBW-4542] We are unable to perform pause/play after closing overlay.

---

js/mixins/componentWidthMixin.js
package.json

* limit rate onResize func fires with resize listener
* the purpose of this update is to avoid costly calculations and component prop updates while window is resizing, see - 
https://lodash.com/docs#debounce

Debounce Resize

---

gulpfile.js

To use React in production mode, set the environment variable NODE_ENV to production -
https://facebook.github.io/react/downloads.html#npm
This also reduces size of bundled app by 54KB

gulp build - process.env.NODE_ENV = 'production'

---

scss/base/_normalize.scss

Prevents ‘zoom-in’ issue with Android in landscape.

[PBW-4145] Ads controls are getting cut in fullscreen.

---

js/components/closed-caption/closedCaptionPanel.js
scss/responsive/_large.scss
scss/responsive/_xsmall.scss

This rollback is for May 2016 release only, latest updates are on feature branch `fcc-settings`

rollback CC options screen to language tab only

---

js/components/scrubberBar.js

when seeked to a point in FF, the scrubber pointer starts from the beginning of the video. This is not seen in Chrome and Safari.
Finding that the point to which the scrubber bar has to move is undefined.
When scrubbing the video, the control first comes here to get the point to which the scrubber pointer has to move(scrubbingPlayheadX). The offsetX which is computed is not recognized in FF because -
**"Although mentioned in the W3 specification, the offsetx/offsety properties themselves are implemented inconsistently across browsers.
While supported in IE, Webkit browsers and Opera, they all function slightly different to the specifications requirements.
The properties aren't supported in Firefox at all - it appears to be a long-time bug that is yet to be resolved."**
This change puts in …

[PBW-4180] Fix seek when low bandwidth results in 'undefined'

---

js/controller.js

* Clear thumbnails data in onEmbedCodeChanged callback

[PBW-5535] Thumbnails from previous asset are shown on the next asset without thumbnails

---

js/components/scrubberBar.js
js/components/thumbnail.js
scss/components/_thumbnail.scss

If mouse is moved slowly, Thumbnail object may go away and a new one will be created.  This object doesn't *know* thumbnail width, so it is zero during initial rendering, which results in wrong placing.  Solution is to save last thumbnail width and pass it as a parameter to next Thumbnail object.  Store this value in Thubmnail static method.

[PBW-5633] [V4] Thumbnails sometimes jump to position that is not aligned with mouse pointing at their center

---

tests/components/controlBar-test.js

⚠️  must merge with https://github.com/ooyala/skin-config/pull/152
html5-skin is design to [exclude logo](https://github.com/ooyala/html5-skin/blob/stable/js/components/controlBar.js#L400) if there is no imageResource url.
This approach allows customers to continue to use custom logo if needed.

[PBW-5518] sync skin with default logo and update unit test

---

js/controller.js

Redid the pull request because I had the wrong branch. Also added Peter's suggested changes.
Original comment:
Eventually, I think it would be better to mimic the behavior of the HTML5 video API in which `muted `and `volume` properties are handled separately. This would allow the user to set an initial volume even if the player starts out muted.
For the scope of this ticket, I think the changes I made should be sufficient though.

[PBW-5876] - Player will now display muted icon when initialVolume is set to 0

---

js/controller.js
tests/controller-test.js

This is the flow that was causing the issue:
1. On Firefox video preloading is enabled, so bitmovin plugin initializes on page load and fires `CAPTIONS_FOUND_ON_PLAYING`.
2. The `video controller` handles this event and then fires `CLOSED_CAPTIONS_INFO_AVAILABLE`.
3. The skin handles this event and uses its info to populate the CC menu.
4. When the video is played, the preroll video is loaded and bitmovin again fires `CAPTIONS_FOUND_ON_PLAYING`, this time with empty captions.
5. The `video controller` again fires `CLOSED_CAPTIONS_INFO_AVAILABLE`, which causes the skin to clear the captions that it had for the main video.
6. When the main video regains focus, the skin is stuck with the captions from the ad (which are empty in this case). 
It's also possible that this issue can occur after …

[PBW-5864] Restoring main video's closed caption settings after ad plays

---

scss/components/_ad-screen.scss

**Edit: I'm going to include another fix, please don't merge yet.**
So the fix is basically just allowing clicks to pass through the pause icon which blocks the video element even when it fades out.  This fix will not work on IE10 or lower, but considering [the list of supported browsers](http://support.ooyala.com/developers/documentation/concepts/pbv4_environments.html) I think this should be ok.

[PBW-5843] - Allowing clicks to pass through pause icon on ad screen

---

js/components/scrubberBar.js
js/controller.js

1.) Afer ad plays or skip button is clicked, ensure playhead is updated with main video playhead, duration, buffer values
2.) Ensure buffer indicator does not exceed 100% of scrubber bar

[PBW-5306] fix playhead position for pre and mid roll ads

---

js/components/adPanel.js
scss/base/_variables.scss
scss/components/_ad-panel.scss

These changes should fix two issues:
- Ads can't be clicked and therefore can't be paused/unpaused on iPad.
- Clicking on an ad on desktop pauses the ad but doesn't trigger a click-through.
Both of these issues only occur when using the **Pulse** ad plugin.

[PBW-5843] Fixed adPanel's z-index when Pulse plugin is active

---

js/constants/constants.js

- Update OO.ERROR.VTC.UNSUPPORTED_ENCODING error description to use OO.ERROR.PLAYBACK.STREAM error's description
- Remove OO.ERROR.PLAYBACK.STREAM error since the message was never published due to an unsupported encoding error, but more appropriately describes the above VTC error message.

[PBI-1970]

---

scss/components/_webvtt.scss

Looks like the CC's where being squeezed between the `top` and `bottom` properties on smaller screens.

[PBW-6113] - Fix for CC's being truncated on iPhone

---

scss/components/_webvtt.scss

Sorry, I saw this after I submitted the previous PR. The CC container wasn't fully expanding, so on iPhone the CC's were growing vertically and it was hard to watch the video.

[PBW-6113] - Increased horizontal space for native CC's

---

js/controller.js

Used for livestream playhead calculation for ads

[PBI-1977] Add current timestamp to INITIAL_PLAY

---

js/components/discoverItem.js
js/components/utils.js
js/controller.js
js/views/contentScreen.js
tests/components/utils-test.js

I also fixed an issue that prevented the end screen's countdown timer from being disabled. I was playing with default props but it turns out that they are applied with a shallow merge, so if the main property is not undefined (like this.props.skinConfig) the nested property defaults don't get applied. I added a helper function to prevent these changes from crashing if the user forgets to define a property on the skin.

[PBW-5932] Implemented text customization for discovery screen

---

README.md
amp_iframe.html
gulpfile.js
iframe.html
js/controller.js
package.json
sample.html
tests/components/scrubberBar-test.js
tests/components/sharePanel-test.js
tests/controller-test.js

1.) Import and bundle skin.json AND all JSON lang files (en, es, zh)
2.) Replace jQuery ajax requests ($.getJSON) with imported skin.json and JSON lang files
3.) update unit test to work with updates
4.) remove config/skin.json param in html files
5.) our html files now require charset utf-8 because language strings are loaded from external js file instead of ajax, this is standard for all multi-lingal sites
6.) if config (skin.json) param or lang jsons (en, es, zh) exist load via ajax for backwards compatibility, else use defaults bundled in app
7.) must be merged with - https://github.com/ooyala/skin-config/pull/154

Bundle skin.json with html5-skin

---

iframe.html

This will automatically get the parent frame's url and use it for analytics, without the customer having to set it via `docUrl`. Passing `docUrl` through the query string will override this.

[PBW-6065] - Automatically setting docUrl to frame's parent url when not explicitly set

---

js/controller.js

The lack of passing the playerParam caused an issue where the ad set code would not get propagated to subsequently clicked discovery videos.

[PLAYER-213] Publish SET_EMBED_CODE with playerParam on discovery click

---

scss/components/_ad-overlay.scss

override 'pointer-events: none' from oo-interactive-container

---

js/constants/constants.js
js/controller.js
tests/controller-test.js

* created `findMainVideoElement()` function to reliably find and set `this.state.mainVideoElement`
* controller has been updated to find mainVideoElement for `onVcVideoElementCreated` and `onPlaying` events
* `bit_wrapper.js` video plugin creates nested video/object element after video is played. `bit_wrapper.js` needs to be updated to create main video element during plugin initialization 
* `this.state.mainVideoMediaType` is also reliably set
* removed some dependency on jQuery

reliably set this.state.mainVideoElement across all video plugins

---

js/components/discoveryPanel.js
js/controller.js
js/skin.js

[Link to ticket](https://jira.corp.ooyala.com/browse/PLAYER-212)
These changes are meant to mimic the way V3 handles autoplay for Discovery videos on iOS. Since we can't show the *Up Next Panel* on fullscreen, we wait until the user exits fullscreen and then we display the countdown. The discovery screen's counter will be used if either `upNext.showUpNext` or `discoveryScreen.showCountDownTimerOnEndScreen` are configured.
This should be merged along with these other PR's:
https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/16
https://github.com/ooyala/html5-video-plugins/pull/258

[PLAYER-212] - Showing Discovery countdown after exiting fullscreen on iOS

---

js/components/controlBar.js
js/components/utils.js
js/controller.js
tests/components/utils-test.js
tests/controller-test.js

* we are using this [deep merge lib](https://github.com/KyleAMathews/deepmerge/blob/master/index.js#L64)
* the custom `arrayDeepMerge` function is passed as a callback to deepmerge function and only used if there is an array in the object that needs to be merged
* Also see - https://github.com/KyleAMathews/deepmerge#arraymerge
* controller updated to subscribe to `OO.EVENTS.SKIN_METADATA_FETCHED` event, returns v3 metadata, deep merges with `skin.json`
* `arrayDeepMerge` function updated to replace buttons by default, prepend after flexible space is also another option
* buttons disabled if `location: "none"`
* `swap` no longer used but still an optional param

onSkinMetaDataFetched and deep merge updates

---

scss/components/_control-bar.scss

[Ticket](https://jira.corp.ooyala.com/browse/PBW-6348)
Since the time display isn't clickable, a customer suggested that we shouldn't display a pointer cursor over it.

[PBW-6348] - Disabling pointer cursor on non-clickable time display

---

js/controller.js

[Ticket](https://jira.corp.ooyala.com/browse/PLAYER-329)
The analytics backend requires that a `Related Videos Displayed` event be fired before a `Related Video Selected`, otherwise the latter event will be discarded. On V4 `Related Videos Displayed` was only getting fired when the Discovery screen was shown, which means that all the Discovery related data was getting lost if the _Up Next_ panel was used.
These changes trigger a `Related Videos Displayed` event when the _Up Next_ panel is first shown.

[PLAYER-329] - Triggering RELATED_VIDEOS_DISPLAYED event when Up Next panel is shown

---

js/controller.js

The timing of subscribing to OO.EVENTS.DISCOVERY_API.RELATED_VIDEOS_FETCHED was too late, sometimes we were subscribing *after* the even was fired. Hence, the discovery was not usable.
I am moving the subscription up, to the earliest point where discovery plugin is already loaded.
[PLAYER-423](https://jira.corp.ooyala.com/browse/PLAYER-423)

[PLAYER-423] moving moving externalPluginSubscription to earlier

---

js/components/accessibilityControls.js
js/controller.js

Seems to be an issue when video returns an error on load. And the keyboard events will still be attached even if the player is unmounted.
Resubmit https://github.com/ooyala/html5-skin/pull/721 to master per request.

Make sure player destroy removes attached keyboard eventlisteners

---

js/controller.js
tests/controller-test.js

-instead of the start screen, the loading screen will be shown when transitioning from an Ooyala ad to the main content

[pbw-6443-transition]

---

js/controller.js
package.json
tests/controller-test.js

[Ticket](https://jira.corp.ooyala.com/browse/PLAYER-760)
The fix for distorted anamorphic videos on Firefox was being applied to both main content and ads. After these changes the fix will no longer be active during ad playback, so the ads will no longer get stretched.

[PLAYER-760] Disabling anamorphic video fix when ads are active

---

js/constants/constants.js
js/controller.js
tests/controller-test.js

[Ticket](https://jira.corp.ooyala.com/browse/PLAYER-1257])
This will essentially remove the loading spinner while the player is loading. The start screen UI will be rendered as soon as possible. If the user clicks on Play before the player is ready, the spinner will be shown at this point and playback will start automatically after `PLAYBACK_READY`

[PLAYER-1257] Perceived Player Performance: Disabling loading spinner during player load

---

js/constants/constants.js
js/controller.js
js/skin.js
js/views/startScreen.js
tests/controller-test.js
tests/views/startScreen-test.js

We will still be removing the spinner during startup, but instead of allowing the user to click on Play before `PLAYBACK_READY`, we will only show the thumbnail until the player is ready to play.

[PLAYER-1257]  Hiding everything but thumbnail until PLAYBACK_READY

---

js/views/playingScreen.js
tests/views/playingScreen-test.js

control bar now is shown hitting the space bar or the enter key into focusable buttons, unit tests added.
more information into the ticket PLAYER-1487 (https://jira.corp.ooyala.com:8443/browse/PLAYER-1487)

PLAYER-1487 fix

---

js/components/accessibilityControls.js
js/components/controlBar.js
tests/components/accessibilityControls-test.js
tests/components/controlBar-test.js
tests/components/scrubberBar-test.js
tests/components/utils-test.js
tests/components/volumeControls-test.js

[PLAYER-1598]
- Added all the pending unit tests for scrubber and volume bar accessibility updates.
[PLAYER-1698]
- Restricting tab navigation to control bar elements when player is in fullscreen mode. Tab focus will loop around on player elements only.

[PLAYER-1598] [PLAYER-1698] Unit tests + Restricting tab navigation on fullscreen

---

js/constants/constants.js
js/controller.js
tests/controller-test.js
tests/html5skin-test.js

The skin will no longer render the loading spinner immediately after the video stalls. When a stalling event occurs the skin will wait for a specified amount of time and then it will render the spinner. If playback resumes before the time elapses the spinner will simply be cancelled.

[PLAYER-1761] Delaying rendering of loading spinner

---

js/controller.js
js/skin.js
tests/controller-test.js
tests/html5skin-test.js

[Ticket](https://jira.corp.ooyala.com:8443/browse/PLAYER-1270)
This will mostly help improve the UX of transitions between videos for Discovery, Playlists and custom carousels.
The following fixes were implemented:
- The skin will now show a single state between videos (loading screen).
- The progress bar of new videos will now start at 0 (it used to flash a full progress bar for about a second and then reset to 0).
- The skin will no longer flash the replay button when transitioning between playlist videos.
- The skin will no longer flash the big play button for videos that have autoplay enabled.
**This PR needs to be merged after this one:**
https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/290/overview

[PLAYER-1270] Perceived performance enhancements (part two)

---

npm-shrinkwrap.json

Without this, `npm install` will keep installing the old version of deepmerge

[PBW-6804] Updating shrinkwrap version of deepmerge

---

js/components/volumeControls.js
js/controller.js
tests/controller-test.js
tests/html5skin-test.js

-skin will now listen to mute state events to change mute state rather than relying on volume values
-updated unit tests for mute states

[player-1897]

---

js/components/closeButton.js
js/components/controlBar.js
js/components/videoQualityPanel.js
js/views/endScreen.js
js/views/pauseScreen.js
js/views/startScreen.js

Buttons that don't have a `type` attribute will default to `type="submit"` in some browsers. This will cause issues if the player is contained within a form element.

[PLAYER-2016] Adding type attribute to all buttons

---

js/controller.js
tests/html5skin-test.js

It looks like mjolnir was updated from this:
```
this.mb.publish(OO.EVENTS.PLAYBACK_READY, {
willAutoplay: this.shouldAutoplay()
});
```
to this: 
```
this.mb.publish(OO.EVENTS.PLAYBACK_READY, timeSincePlayerCreated, {
willAutoplay: this.shouldAutoplay()
});
```
So this was breaking the changes from PLAYER-1270.
I think we should disallow updates that change the order of parameters in message bus events, since any existing listeners that expect the current order will break. It's probably also a good idea to have all parameters inside an object so that you can easily add new ones without having to worry about the order.

[PLAYER-1270] Adapting to latest mjolnir changes

---

js/controller.js

This should be merged together with the following PR:
https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/326/overview
The skin triggers `SET_CLOSED_CAPTIONS_LANGUAGE` every time the video resumes playback, so this was causing closed captions to disappear on fullscreen iOS when pausing and then resuming. The core uses the `isFullScreen` parameter to determine whether to show the native closed captions on iOS or not, so this state was being lost.

[PLAYER-1992] Passing isFullScreen parameter when firing SET_CLOSED_CAPTIONS_LANGUAGE event

---

js/controller.js
tests/html5skin-test.js

-skin will set currentVideoId earlier on vc play rather than vc playing. This will allow initial volume to pass through

[player-2144]

---

js/components/videoQualityPanel.js
js/constants/constants.js
js/constants/macros.js
tests/components/videoQualityPanel-test.js

-removed “quality level” aria label for bitrate only video quality selections
-added tiered resolutions for resolution only video quality selections
-moved button creation outside of the render function into a separate function

[player-2011]

---

js/controller.js
tests/html5skin-test.js

Video 360 should not be blured on pause (videoVr should not blur). This is because even for paused video user is able to look around and this is useless for blured video.
If we have Video360 then we don't set class to blur the player.
Unit tests added.

[bugfix/PLAYER-2220]: videoVr should not blur on pause.

---

js/controller.js
tests/html5skin-test.js

Video 360 should not be blured on pause (videoVr should not blur). This is because even for paused video user is able to look around and this is useless for blured video.
If we have Video360 then we don't set class to blur the player.
Unit tests added.

 [bugfix/PLAYER-2220]: videoVr should not blur

---

js/components/utils.js
js/controller.js
tests/components/utils-test.js
tests/html5skin-test.js

[Ticket](https://jira.corp.ooyala.com/browse/PLAYER-2672)
Bitrates published `BITRATE_INFO_AVAILABLE` will now be presorted, but in the special case where only bitrates are displayed (without resolution) then the skin needs to do some additional sorting in order to display the bitrates in ascending order.
This could've potentially been handled by the VTC as well, but I thought it shouldn't be concerned about display related stuff.
This needs to be merged together with the following PR's:
https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/422/overview

[PLAYER-2672] Sorting video qualities by bitrate when only bitrate is displayed

---

js/controller.js
js/views/playingScreen.js
tests/html5skin-test.js
tests/views/playingScreen-test.js

[Ticket](https://jira.corp.ooyala.com/browse/PLAYER-2102)
This will basically just prevent the control bar from flashing briefly when a new Discovery or Playlist video is first shown. These changes also prevent the start screen from flashing during video transitions. This last issue had already been fixed, but was re-introduced recently.
I also refactored some old unit tests in order to avoid re-declaring a large mock object on each separate test.

[PLAYER-2102] Preventing control bar from flashing during video transitions

---

tests/components/controlBar-test.js

This unit test is breaking because the `multiaudio` icon was removed from the skin config but the skin code wasn't updated. I will just disable this for now since this seems to have been addressed in this PR: https://github.com/ooyala/html5-skin/pull/1032
It also looks like this unit test has been removed from that PR.
FYI @KseniiaSokolovaEpam @yaroslavgribov @DmitriiMaslov

[PLAYER-2962] Disabling unit test temporarily since required icon has been removed

---

.eslintrc
package.json

This PR introduces a new feature - ESLint(Linting utility for js and jsx). It's not in any case a single source of truth, it's just and attempt to start a discussion. Some of the rules are taken from the styleguide, some are just recommended and community-wide adopted best practices. We could add more rules as we progress.
ESLint is an awesome tool that could allow us enforce code style rules, reduce the number of code style comments in PR and help us write better code overall. It has integrations with pretty much every editor and is really easy to setup and use.
The purpose of this PR is to introduce the feature, essentially it does not affect any aspect of the development at this point, but it might be used later at the build stage, CI, etc.
ESLint can be installed both globally and …

Add ESLint and ESLint run command in package.json

---

js/components/closed-caption-multi-audio-menu/closedCaptionMultiAudioMenu.js
js/components/closed-caption-multi-audio-menu/tab.js

We hide CC column in new Multi-Audio menu for the first release only.
(When a new design is existed and CC settings are moved to menu as well then CC column will be shown again.)
Old unit tests are passed.
There is no nessaccary to create new tests.

[feat/PLAYER-3234] Hide CC column in new Multi-Audio menu

---

js/constants/constants.js
js/views/errorScreen.js
tests/views/errorScreen-test.js

Add error codes 22 and 29 to the list.
- [PLAYER-634](https://jira.corp.ooyala.com/browse/PLAYER-634)
- [459](https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/459/overview)
- [309](https://git.corp.ooyala.com/projects/PBW/repos/video-plugins-internal/pull-requests/309/overview)
- Unit tests passsed
- added tests for errorScreen as it seems to be the main cornerstone in this case
- codestyle
- prop types

[bugfix/PLAYER-634] Add error codes constants

---

js/components/closed-caption/closedCaptionPopover.js
js/components/controlBar.js
js/components/moreOptionsPanel.js
js/constants/constants.js
js/controller.js
js/skin.js
js/views/contentScreen.js
tests/components/closedCaptionPanel-test.js
tests/html5skin-test.js
tests/skin-test.js

Fix the issue that  window CC is closed after change a language.
CLOSED_CAPTION_SCREEN is used instead of CLOSEDCAPTION_SCREEN in the skin plugin.
No tests are needed.

Bugfix/player-3314 to master Language selection closes the CC window

---

js/components/closed-caption-multi-audio-menu/closedCaptionMultiAudioMenu.js
js/components/closed-caption-multi-audio-menu/multiAudioTab.js
js/components/controlBar.js
tests/components/closed-caption-multi-audio-menu/closedCaptionMultiAudioMenu-test.js

Fixes an issue where title from constants was used instead of retrieving localized string.
- [PLAYER-3296](https://jira.corp.ooyala.com/browse/PLAYER-3296)
- Added a test to verify that string from translations is used in rendering

[bugfix/PLAYER-3296] Add localized headers to CC and MA menus

---

js/components/controlBar.js

Use translated "Audio" instead of untranslated "Multi Audio"
[Original task])(https://jira.corp.ooyala.com/browse/PLAYER-3580)
No tests needed

[bugfix/PLAYER-3580] Audio instead of MultiAudio as a text for tooltip

---

.eslintrc
js/components/controlBar.js
js/components/utils.js
tests/components/controlBar-test.js
tests/components/utils-test.js

There is function "isMobile" which checkes if a user device is phones or tablets. And returns true if the device is phone or tablet. But we need to show a carbord icon only on phones (exept tablets).
So now we have function "getUserDevice" for checking type of the user devices ( which returns one of values: phone, tablet or desktop). And if the device is phone we show the icon.
And there are 2 changes for ESLint (in utils.js line 617 and controlBar.js line 638)

[bugfix/PLAYER-3751] Cardboard icon is visible on tablets

---

js/controller.js
tests/html5skin-test.js

Fixes an issue in which rewind doesn't happen if `loop=true`. Also added the first set of unit tests for the Skip Controls. Will continue adding more of these.

[PLAYER-3835] Fix for rewind with loop + controller unit tests for Skip Ctrls

---

js/controller.js
tests/html5skin-test.js

Now we have a situation for HA video: when second subchannel starts playing function '_removeFocusFromElement' is called; videoId is 'reload' now. After that function 'vcFocusVideoElement' is called, and videoId is becoming 'main', and it is last time when Object { main: {…}, reload: {…} } exists. After that the object is { main: {…} }, but in skin state 'currentVideoId' (which we use for setting audio) is still 'reload'. And when user click on a track from MA list we return from the function because Object['reload'] does not exist.
So, now we change value of currentVideoId in skin to value of videoId in mjolnir.
In the test we check if the value of currentVideoId is correct.

[bugfix/PLAYER-3847] Not able to change audio track after failover to subchannel2

---

js/components/playbackSpeedPanel.js
js/components/utils.js
js/controller.js

These updates allow handling the case in which playback speed is set via API to a value that is not one of the predefined values. The UI will now update and include the new value in the list.
Note: Unit tests are still pending, will add in a future PR.

[PLAYER-3645] Allowing UI to react to API speed changes

---

js/components/closed-caption-multi-audio-menu/helpers.js
tests/components/closed-caption-multi-audio-menu/helpers-test.js

If we get langCode === '' we should not use it to find name in the language map ; we need to set displayLanguage to ''.
[Origin task](https://jira.corp.ooyala.com:8443/browse/PLAYER-4018)

[bugfix/PLAYER-4018] langauge code 'und' is translated to 'qafaraf' instead of 'undefined langauge'

---

js/components/controlBar.js
tests/components/controlBar-test.js

I had missed this little detail. The control bar buttons get the highlight color when their respective popover menu is open.

[PLAYER-3645] Highlighting Playback Speed button when menu is active

---

js/controller.js
tests/html5skin-test.js

-will set multiAudio state to null if we receive less than 2 tracks (effectively hiding the multi audio icon)
PLAYER-4080 was occurring because the video element is throwing an audio change event on a single audio track, which sends out a multi audio changed event with only 1 audio track. This makes our skin show the multi audio icon. This looks to be a native Safari issue. To workaround this, I've modified the skin to set the multi audio state to null if we receive a multi audio changed event with less than 2 tracks.

[player-4080]

---

js/controller.js
tests/html5skin-test.js

When an user use only tilting we do not have correct value for viewing direction. So we forcibly check the viewing direction when AD starts and set this value when AD ends.
(And some changes for eslint.)

bf/PLAYER-3750 View direction is reset to initial position after AD for tilting

---

js/views/pauseScreen.js
js/views/playingScreen.js

Page was scrolled when user tried to navigate the video 360 via touch&drag in window mode.
Document touch event listeners are now passive by default in Safari 11.1, which is bundled with iOS 11.3 (this change is documented in the [Safari 11.1](https://developer.apple.com/library/archive/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_1.html) ) so because of that preventDefault in the callback did not work to prevent scrolling.
Tests are not needed.

[bugfix/PLAYER-4226] Page is scrolled when user tries to navigate the video by touch&drag

---

js/components/directionControlVr.js
js/components/viewControlsVr.js
js/views/playingScreen.js
tests/components/directionControlVr-test.js
tests/components/viewControlsVr-test.js

Prevent dowble call rotation method.
Move to es6 syntax.
The [associated PR](https://git.corp.ooyala.com/projects/PBW/repos/video-plugins-internal/pull-requests/350)

bugfix/PLAYER-3966 View direciton is not reset to initial from the first time via on-screen contorl

---

scss/html5-skin.scss

These styles were only meant for the debug page and can cause conflicts if customers have elements with the `video_container` id, for example. 
**IMPORTANT**
Before deploying this to candidate we need to merge this PR and deploy the debug page changes:
https://git.corp.ooyala.com/projects/PBW/repos/hack_attack/pull-requests/13/overview

[PLAYER-4428] Removing debug page styles from skin CSS

---

js/components/controlBar.js
js/controller.js
tests/components/controlBar-test.js
tests/html5skin-test.js

This branch contains the needed logic to enable/disable the chromecast button by using a player param with the following structure:
```
"chromecast": {
"enable": true
}
```

[PLAYER-4543] Enable/Disable chromecast button by page player param

---

js/skin.js

This branch contains the fix for restore the `responsiveClass` state at skin.js. Also mixes it with the `.oo-responsive` class.

[PLAYER-4542] Controls look too big on mobile devices

---

js/controller.js
tests/components/controlBar-test.js
tests/html5skin-test.js

The player will now use the `playerType` page-level param in order enter audio-only mode instead of the `audioOnly` value from the skin.

[PLAYER-4385] Now reacting to playerType page-level param

---

js/components/higher-order/holdOnClick.js
js/components/skipControls.js
tests/components/higher-order/holdOnClick-test.js
tests/components/skipControls-test.js

The "Skip Forward" button will basically be greyed out and disabled when the video has ended. This is mostly for the audio-only player, but the behavior should be consistent for all player types.
Note that this doesn't fully fix the issue from PLAYER-4582, this is just a partial update for now.

[PLAYER-4582] Disabling Skip Forward button when at video end

---

js/components/slider.js
scss/components/_slider.scss
tests/components/slider-test.js

This fixes an issue in which the CC menu slider couldn't be dragged with the mouse on Firefox. It also maintains the behavior in which the blue focus outline is not shown while interacting with the mouse, but is activated when using the keyboard.

[PBW-7594] Fixing slider drag action on Firefox

---

js/components/castPanel.js
js/components/controlBar.js
js/components/icon.js
js/constants/constants.js
js/controller.js
js/views/endScreen.js
js/views/higher-order/withAutoHide.js
js/views/pauseScreen.js
js/views/playingScreen.js
scss/base/_variables.scss
scss/components/_state-screen.scss
scss/responsive/_large.scss
scss/responsive/_xsmall.scss
tests/components/castPanel-test.js
tests/components/controlBar-test.js
tests/html5skin-test.js
tests/skin-test.js
tests/views/endScreen-test.js
tests/views/higher-order/withAutoHide-test.js
tests/views/pauseScreen-test.js
tests/views/playingScreen-test.js

This branch contains the needed modifications to show a panel information about the device used to cast the content through Chromecast.
These are the modified screens and his behaviour:
- **PlayingScreen**: It will show a panel in the middle of the screen with the device name. Right now has a little consideration for when the `skipControls` are enabled and it will be placed below this controls.
- **PauseScreen**: As the above screen, a panel will be shown in the center of the screen and it could react to be placed below of the `skipControls`, if active.
- **EndScreen**: At the end of the video, the size of the replay button will be a little bit smaller just to make room to place the device information just below of it.
As a general rule for all the screens, whether or not the controlBar …

[PLAYER-4369] Add in ui element to show that you are casting

---

js/components/castPanel.js
js/views/endScreen.js
js/views/pauseScreen.js
js/views/playingScreen.js
scss/components/_state-screen.scss
tests/components/castPanel-test.js
tests/views/endScreen-test.js
tests/views/pauseScreen-test.js
tests/views/playingScreen-test.js

The problem:
Play/Pause is not working on clicking the centre of player
This is regression issue introduced with 4.29.6.
My solution:
Play/pause does not work because a cast panel is located here. It was a problem for me when I worked on issue with vr, but to I added that time "display": "none" property, but now I think that it would be better to remove the element at all, when player is not using as cromecast. So I removed it in this case.

[bugfix/PLAYER-4774] Play/Pause is not working on clicking the centre of player

---

js/components/unmuteIcon.js
tests/components/unmuteIcon-test.js

This update fixes an issue in which clicking on the "unmute" button during an ad would also trigger a click on the `AdScreen`, which in turn would trigger the ad's clickthrough.
**Note:** I don't think this is an urgent issue so it's probably better not to include this on the candidate build yet.

[PBW-7601] Preventing unmute button click from triggering ad clickthrough

---

scss/components/_unmute.scss

The problem:
Screens has button mute/unmute on the left top of the screen.
When ad is playing and an user click on the btn Instead of muting/unmuting the video, ad url is opened.
My solution:
On ad-screen "pointer-events" is "none";
This value is inherited to the btn.
So, I changed this value for the btn, and remove blue border when the element is in focus.

[bugfix/PBW-7632] unmute btn is clickable

---

js/controller.js
js/skin.js
tests/html5skin-test.js
tests/skin-test.js

The problem:
Total Duration of asset is not shown on start screen.
The reason:
The value for "duration" was in State, and it was changed in "updatePlayhead", where new state value was count within function Utils.ensureNumber using itself.
The solution:
Return promise from updatePlayhead and resolve it once setState in there is done
Unit tests passed

[bugfix/PLAYER-4575] Total Duration of asset is not shown on start screen, it is shown as 0:00

---

scss/components/_unmute.scss

The style was placed in right placed (from inner div to outer one).

[bugfix/PWB-7632] pointer-events for oo-unmute in right place

---

js/controller.js

There's a comment below about `END_SCREEN_SHOWN`. Does anybody have an idea?
Also we need a plan how to deal with event system. Now it's a mess.

force `renderSkin` to show end screen after the video has been played

---

scss/components/_ad-panel.scss

A value for "pointer-events" for skip btn should be "auto" instead of inheritable value "none" to be clickable.

[bugfix/PBW-7632] pointer-events: auto for skip btn

---

gulpfile.js
js/controller.js
js/index.js
tests/html5skin-test.js
webpack.config.js

Somebody already implemented this for Android, but didn't do the same for iOs.
Fix led to problems with shared state in unit tests, that's why there are so many changes. The main idea is to avoid global mutable object shared between tests.

fix pause on AD on iOs.

---

js/views/pauseScreen.js
js/views/playingScreen.js
tests/views/pauseScreen-test.js
tests/views/playingScreen-test.js

After an ad value for buffering is false.
And sometimes we do not have any events when an ad is ended and a main video is not playing yet. It is become visible especially with bad internet connection (for exemple, slow 3g).
So in this case if nothing buffered yet, but buffering state is false we should show spinner.
Also this behavior was added for pauseScreen.

bugfix/PBW-7731 How to set loading bar at the black screen

---

scss/base/_normalize.scss

Now if audio stream contains video it will be shown. This solution is a workaround, SAS shouldn't send video chunks in audio only stream
`.oo-video-player` class appears only for video assets: https://github.com/ooyala/html5-skin/blob/master/js/controller.js#L1714-L1717

[PLAYER-4881] hide video element for audio only asset

---

js/views/pauseScreen.js

when casting if I pause video playback and then reload current tab pauseScreen will be rendered with a Spinner (since the buffer prop is 0 until playback's started)
https://jira.corp.ooyala.com/browse/PLAYER-4366
Version:4.30.9
Status: Failed
Debug link: https://tinyurl.com/ya2rd85q
Steps:
1. Open the debug link
2. Connect to chromecast
3. Video plays on receiver
4. Pause the video on sender 
5. Refresh the page
6. Player rejoins the session but loading spinner is still shown in player. loading spinner disappears on clicking on 'Play' button(Refer to video attached)

[PLAYER-4366] Chromecast auto rejoin fix

---

js/components/utils.js
tests/components/utils-test.js
tests/html5skin-test.js

Now a default language is the most prioritise language.
New language selection logic for UI:
- if we can get user language, and this language is in the list of available languages, then we use this language
- if we can get user language, but this language is not in the list of available languages, then we use the default language
- if it is impossible to determine the user's language, then use the default language
\
\
\
Extra information:
At the beginning of the player starts, the "getLanguageToUse" function is called twice: when the function "onPlayerCreated"  is called (here we get the value from skin.json) and when function "onSkinMetaDataFetched" is called (here the value from skin.json is overridden by the value from page-level params).

[bugfix/PLAYER-4606] Use the browser settings over skin.json

---

js/controller.js

Adding null check for discoveryData to prevent errors.

[PLAYER-5025] - Issue when exiting the full screen mode once the video finishes playback

---

js/index.js
npm-shrinkwrap.json

Babel-polyfill throws an exception when discovers that another babel-polyfill appeared on the page. Import as noConflict seems to eliminate the issue. Checked this with CharlesProxy.

babel-hotfix: noConflict import done

---

js/controller.js

[Jira Link](https://jira.corp.ooyala.com/browse/PLAYER-5026)
Corresponding PRs for [Receiver](https://github.com/ooyala/chromecast-sample-receiver/pull/68) and [Sender](https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/618/overview)
This issue manifests itself when playback is done and I want to reload the page (when casting)
Steps:
* Open the debug link: https://tinyurl.com/yc2my2c8
* Connect to chromecast
* Video plays on receiver
* Refresh the page when playback's ended
* Player shows the start screen with play button but on clicking the play button it buffers indefinitely

[PLAYER-5026][WEB][Chromecast] Reload the page when casting

---

js/controller.js

Removed renderSkin() from onWillPlaySingleAD because of Webview default image appearing.
This was fixed previously by removing this renderSkin(), but it led to ssai issues.
https://jira.corp.ooyala.com/browse/PBW-7648

[fix/PBW-7648] The default image appears on Mobile webview

---

js/components/controlBar.js
tests/components/controlBar-test.js

Icons for audioOnly on controlBar was moved in skin-config to outer object. That was the reason of the bug.
Key "desktop" for the icons was added, 
also an error (when method "filter" was called on undefined (this.props.skinConfig.buttons.audioOnly)) was fixed.
[Connected PR](https://github.com/ooyala/skin-config/pull/231)

[bugfix/PLAYER-5111] Player controls are not coming up with Audio only player

---

js/components/utils.js
js/controller.js
npm-shrinkwrap.json
tests/components/utils-test.js
tests/html5skin-test.js

New logic to choose default language
1. if "useBrowserLanguage" is set to true
try to check browser language,
if it is checkable, use it as a default language,
if it is not checkable, use defaultLanguage from inline props on page-level params,
if it is not checkable and defaultLanguage on page-level params is not set, use default language
2.  if "useBrowserLanguage" is not set to true
use defaultLanguage from inline props on page-level params,
defaultLanguage on page-level params is not set, use default language
Unit tests passed

[feature/PLAYER-4606] default UI language: Use the browser settings over skin.json with page-level param

---

js/components/adPanel.js

Recently Ksenia added the Spinner to the AdScreen so we should remove the Spinner from the AdPanel which is used inside the AdScreen with condition of 'showAdMarquee'.
https://jira.corp.ooyala.com/browse/PLAYER-5160

[fix/PLAYER-5160] v4] Double loading spinner on ads

---

js/components/controlBar.js
js/constants/constants.js

ariaLabel is required param so this fix is removing a warning of proptypes

Added AriaLabel param for airPlay

---

js/controller.js

https://jira.corp.ooyala.com/browse/PLAYER-5095

[fix/PLAYER-5095] Trigger targetPicker only after 'playing' event

---

scss/components/_discovery-panel.scss
scss/components/_state-screen.scss
scss/mixins/_mixins.scss

35px is not enough for a timer , when the timer includes hh:mm:ss,
"Width" was change to "min-width" and "flex-shrink" was added to prevent the possibility of compressing the element

[bugfix/PLAYER-5164] Audio-Only player control alignment issue

---

js/controller.js

https://jira.corp.ooyala.com/browse/PLAYER-5204
case 1: 
load an asset with airplay enabled
try loading another asset in the same window with airplay set as false
airplay continues with the existing session
but in this case, the user would not be able to opt out of airplay (since the icon would no longer be visible).

[fix/PLAYER-5204] Add page-level parameter to disable AirPlay option

---

js/views/audioOnlyScreen.jsx

Fixed the audio-only screen after the eslint fixes.
Apparently the wrapper was absent after eslint PR.
` <div className="oo-state-screen-audio oo-flex-column-parent">`

[fix] Audio only screen

---

js/controller.js
tests/html5skin-test.js

Should I add additional check to the core.js? (in ChromecastSender.js)
to not load this module completely
```
if (OO.isChrome && OO.isSSL && !OO.isIos) {
}
```
or this check is sufficient? (just in Html5Skin)

[PLAYER-5216] Show console warning when cast enabled but blocked

---

js/views/adScreen.jsx
tests/views/adScreen-test.js

There was an checking if(this.isMounted ()) {...}, but function "isMounted" never existed, so when the window was resized (switching to fullscreen mode), the function was called and there was an error.

bugfix/PLAYER-5242 Player controls are not displayed on fullscreen

---

js/components/countDownClock.jsx

After migration to ES6 the execution context of canvas method was lost due to object destructuring: canvas method was assigned to dedicated constant and dot operator that established context originally got removed. Fixed this by explicit passing the context via .call method.

fix/PLAYER-5724 canvas context was lost due to object destructuring, fixed this

---

js/views/playingScreen.jsx
scss/components/_playing-screen.scss

Hide the cursor when the control bar get hidden on fullscreen mode

[PLAYER-254] Autohide cursor in full-screen mode when the control bar also auto-hides

---

js/controller.js

[Jira Link](https://jira.corp.ooyala.com/browse/PLAYER-5383)
when player is created
```javascript
OO.Player.create("ooplayer", asset, playerparam);
```
core.js publishes **PLAYER_CREATED** event and then defers **ASSET_CHANGED** event
```javascript
mb.publish(OO.EVENTS.PLAYER_CREATED);
...
_.defer(() => {
this.mb.publish(OO.EVENTS.ASSET_CHANGED, asset, params);
}); // === setTimeout(cb, 0)
```
PLAYER_CREATED -> stack is empty -> ASSET_CHANGED
-------------
in Skin.js on **PLAYER_CREATED** event **this.skin** is assigned _asynchronously_ if there's a skin config link in the params
```javascript
mb.subscribe(OO.EVENTS.PLAYER_CREATED, (params) => {
if (params.skin.config) {
$.getJSON( params.skin.config, () => this.skin = ReactDom.render());
}
})
```
so when deferred **ASSET_CHANGED** event …

[PLAYER-5383] Cannot read property updatePlayhead

---

js/components/controlBar.jsx
tests/components/controlBar-test.js

I have removed the airplay button for Iphones because the IOS native AirPlay control button in the full-screen mode can not fully synchronize with our AirPlay button.

[PLAYER-5104] [v4] [airplay] video doesnt play on turning off airplay using native (IOS) airplay option

---

scss/skin/_default.scss

That css `.oo-fullscreen` width and height were being overwritten.
https://jira.corp.ooyala.com/browse/PLAYER-5404

[PLAYER-5404] web IE videos do not play on fullscreen

---

js/components/scrubberBar.jsx

`endSeeking` sets `seeking` property to `false`. It happens right after the seeking was started and causes flickering of the playhead.
corresponding pr to bitwrapper: https://git.corp.ooyala.com/projects/PBW/repos/video-plugins-internal/pull-requests/411/overview

[PLAYER-5512] fix seeking on live streams

---

js/controller.js
js/views/audioOnlyScreen.jsx
tests/views/audioOnlyScreen-test.js

https://jira.corp.ooyala.com/browse/PLAYER-5283
There is a new param in skin config - "displayTitleOnVideoCanvas". It is currently available on staging.
[The debug link](http://debug.ooyala.com/ea/index.html?ec=JmNHcwaDE6dJZ3gIB9dSsqo_3GvrXv3D&pbid=12a647f6b8ae4cb5a097eec8ec779b43&pcode=c0cTkxOqALQviQIGAHWY5hP0q9gU&core_player=%2F%2Fplayer-staging.ooyala.com%2Fcore%2F12a647f6b8ae4cb5a097eec8ec779b43&video_plugins=.&trackingLevel=unset)

[PLAYER-5283] Respect Backlot flag for "Show image above player" flag for Audio Only Player

---

package.json

This branch updates the screenfull version from 3.3.3 to 4.2.0 to enable fullscreen on IE

[PLAYER-5561] IE Fullscreen not working

---

js/controller.js

`uiLanguage` is set only in `loadConfigData` where we load additional localizations. When it's set we don't need to load another localizations

[PBW-8035] prevent loading unneeded localization

---

js/components/scrubberBar.jsx
tests/components/scrubberBar-test.js

Currently, scrubber bar has own state which is updated both after user interaction and `PLAYHEAD_TIME_CHANGED`, which creates flickering because of the inconsistent playhead value. The main point is to update the scrubber bar only on `PLAYHEAD_TIME_CHANGED` event.
corresponding PR in BitWrapper: https://git.corp.ooyala.com/projects/PBW/repos/video-plugins-internal/pull-requests/420/overview

[PLAYER-5512] fix ScrubberBar flickering

---

js/components/controlBar.jsx

Previous investigation from Aleksander Afanasev:
«I have checked this on Iphone X and looks like IOS native AirPlay control button in the full-screen mode can not fully synchronize with our AirPlay button. So, in order to resolve this issue I suggest to remove our AirPlay button from control bar for Iphones. As for IPAD, it can render our control bar in full-screen mode and it doesn't have the native controls, so it works fine.»
Since QA reports the issue remains for IPAD, I expand original solution to all IOS based devices: IPhone, IPad when AirPlay is available.

fix/PLAYER-5104 hide fullscreen button for on Ios when AirPlay available
