ooyala/html5-skin

js/components/controlBar.js, js/controller.js
-NaN time will be replaced by formatted 0
-end time on end screen is updated to reflect the latest passed video duration (was taken from content tree before)
=> [PBW-3166] NaN time will be replaced by formatted 0.

js/controller.js
- fixes the problem with end screen shown when scrub back from the end screen using iOS controls.
- also modifies 2 places that were affected by PAUSED event previously replaced by STREAM_PAUSED
=> [PBW-3507] 

js/components/controlBar.js, js/components/moreOptionsPanel.js
corresponds with config/skin PR - https://github.com/ooyala/skin-config/pull/86
=> [PBW-3506] update control bar icon color to white

js/styles/inlineStyle.js
fix for broken moreOptions screen animation
=> [PBW-moreOptionsAnimation] animation for moreOptions is back

js/views/pauseScreen.js, js/views/startScreen.js, scss/base/_base.scss, scss/base/_variables.scss, scss/components/_discovery-screen.scss, scss/components/_state-screen.scss, scss/mixins/_mixins.scss
merge this into `pbw-3634-screens` before merging `pbw-3634-screens` into master
=> UX font tweaks

js/components/discoveryPanel.js, js/views/discoveryScreen.js, scss/components/_discovery-screen.scss
=> Add pagination arrows to Discovery

js/constants/constants.js, js/controller.js
Works with http://github.services.ooyala.net/Platform/mjolnir/pull/466.
=> [PBW-4021] pauseAnimationDisabled on VC_PAUSED passing "transition"

js/constants/constants.js, js/views/errorScreen.js
Works with https://github.com/ooyala/skin-config/pull/102, please merge after that one is merged.
- adding error message for:
-- OO.ERROR.VC.UNSUPPORTED_ENCODING
-- OO.ERROR.VC.UNABLE_TO_CREATE_VIDEO_ELEMENT
- changing error message for
-- UNKNOWN_ERROR
=> [PBW-3762] adding new error codes and changing unknown error message

sample.html
This new inline embed source will be updated automatically with our stable deployments.
=> [PBW-4095] added inline embed source to sample.html

js/components/controlBar.js, js/controller.js, js/views/endScreen.js, js/views/pauseScreen.js, js/views/playingScreen.js
-- Volume slider appears for Android when volume button is touched
-- If Volume button is touched while slider is shown, mute functionality works
-- Volume slider is hidden after Control Bar hides or is unmounted
=> [PBW-4096] volumeSlider for Android appears on touch

js/components/controlBar.js, js/controller.js
should work with https://github.com/ooyala/skin-config/pull/108
=> [PBW-4214] rendering bitrate selection icon in CB

js/components/controlBar.js, js/components/discoveryPanel.js, js/skin.js
works with - https://github.com/ooyala/skin-config/pull/109
=> Responsive Breakpoints config/skin.json

js/components/closedCaptionPanel.js
Fixes localization on sample text.
=> [PBW-4178] Localization on sample text

js/controller.js
Adds an END_SCREEN_SHOWN event to onPlayed.
=> [PBW-4142] User have to tap twice to replay the postroll video

scss/base/_type.scss, scss/base/_variables.scss
Adding a variable to define the font paths in the CSS.
=> [internal] Make fonts paths quickly configurable

js/components/controlBar.js, js/components/moreOptionsPanel.js, js/controller.js
also, discovery on pause and on end not called if relatedVideos.videos is not defined.
=> [PBW-4205] Discovery button not shown if no discovery data

js/controller.js
Passing real bitrate info from VTC, removed test code
=> [PBW-4213][VTC] Publish AVAILABLE_BITRATE events

js/skin.js, tests/components/controlBar-test.js, tests/controller-test.js
id attr is to get ready for automated testing
=> Add id attr to responsive div and fix unit tests

js/components/controlBar.js, scss/components/_control-bar.scss, tests/components/controlBar-test.js
Works with https://github.com/ooyala/skin-config/pull/113
=> [PBW-3181] watermark made clickable when clickUrl specified in skin.json

scss/components/_share-screen.scss
Related PRs: 
https://github.com/ooyala/skin-config/pull/115
http://github.services.ooyala.net/Platform/player-v4/pull/19
=> [PBW-4508] changing paths for social icons to absolute

assets/images/loader_svg.svg
Received a better version of loader image from UX
=> [PBW-4510] changing image to a new one

js/controller.js
Added passing the playerParams to the SET_EMBED_CODE event.
(matching change to mjolnir mentioned in original check-in was NOT made as it was unnecessary.)
=> [PBW-3542] autoPlay not working after UpNext countdown

js/components/slider.js
handles coloring for webkit browsers in case input value was changed not from the input itself (pressing mute button, for example)
=> [PBW-4287] coloring after mute fix

scss/components/_scrubber-bar.scss
Changes cursor to pointer over scrubber bar.
=> [PBW-4243] Change cursor to pointer over scrubber bar

js/views/pauseScreen.js, js/views/startScreen.js
- check if description is rendered before calling Utils.truncateTextToWidth
- using different skin config parameters for start and pause screen
=> [PBW-4006] fixes description set to false breaking the pause screen

js/components/adOverlay.js, js/components/controlBar.js, js/components/scrubberBar.js, js/components/upNextPanel.js, js/constants/constants.js, js/views/adScreen.js, js/views/endScreen.js, js/views/pauseScreen.js, js/views/playingScreen.js, scss/base/_utilities.scss, scss/base/_variables.scss, scss/components/_ad-overlay.scss, scss/components/_control-bar.scss, scss/components/_scrubber-bar.scss, scss/components/_state-screen.scss, scss/components/_text-track.scss, scss/components/_up-next-panel.scss, scss/responsive/_xsmall.scss, tests/views/playingScreen-test.js
to avoid overlap with other UI components
=> [PBW-4575] CC relative position

js/controller.js, scss/base/_base.scss, scss/html5-skin.scss, scss/skin/_default.scss
* main purpose is to enforce min player width of 320px
=> [PBW-4810] Add new container class name

js/controller.js
works with https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/11
=> [PBW-4347] discovery for unbundled player

scss/components/_text-track.scss
set white-space to pre-wrap so caption text will wrap on line breaks
=> [PBW-4643] Preserve Caption Line Breaks

scss/components/_control-bar.scss
This is an urgent fix that needs to be merged otherwise the control bar animation is broken.
=> [PBW-5077] Bug fix for control bar animation.

scss/base/_variables.scss, scss/components/_video-quality.scss
With the new control bar changes the pop over height needed to be adjusted.
=> [PBW-5187] Updates to the bitrate pop-over height

scss/components/_control-bar.scss, scss/responsive/_xsmall.scss
With new control bar updates the "LIVE" text and red "dot" needed to be readjusted and updated.
=> [PBW-5189] updates to live text and dot

js/components/controlBar.js, js/components/utils.js
* Don't display current time for live stream unless we shifted to the past in which case show negative value related to current time
=> [PBW-5214] Update time counter on control bar Live stream

js/controller.js
Resolve - Uncaught exception TypeError: Cannot read property 'addEventListener' of undefined
=> [PBW-5158] resolve - Cannot read 'addEventListener' of undefined

js/components/controlBar.js, scss/components/_control-bar.scss
* Converted "live" div to button, added click handler for this button
=> [PBW-4954] [Alice] Trigger seek-to-end (duration) when live button is clicked

js/components/controlBar.js, js/constants/constants.js, scss/base/_variables.scss, scss/components/_control-bar.scss, scss/components/_scrubber-bar.scss, scss/responsive/_xsmall.scss
⚠️  must merge width - https://github.com/ooyala/skin-config/pull/140
=> update style and config to sync with icon updates

scss/components/_scrubber-bar.scss, scss/responsive/_xsmall.scss
=> fix playhead centering

js/views/startScreen.js, scss/components/_start-screen.scss
moved to different elements for better configuration
=> separate start screen background image and gradient

scss/components/_share-panel.scss
* build script will change to stable version
* ⚠️  must merge with - https://github.com/ooyala/skin-config/pull/141
=> update absolute paths to /candidate/latest/

scss/components/_closed-captions.scss, scss/responsive/_large.scss, scss/responsive/_xsmall.scss
=> [PBW-5249] rollback cc on-off switch style

js/components/scrubberBar.js
* For html5 live HLS assets main_html5 reports duration == 0 and scrubbaer bar shouldn't be doing calculations
=> [PBW-5275] [Alice][Live Stream] Showing NAN:NAN if Live Stream assets are scrubbed

js/components/tabs.js, package.json
* consider swapping scrollbar component in `videoQualityPanel.js`
=> swap react-scrollbar component to prevent breaking input range slider

scss/components/_tabs.scss
=> Left align CC option tabs

js/skin.js
This resolves blank social title issue
=> [PBW-5556] add content tree to share panel props

gulpfile.js
Related to https://github.com/ooyala/html5-skin/issues/543
=> Add gulp task for apps using React.js externally

js/components/controlBar.js, js/constants/constants.js, js/skin.js
This is related to : https://github.com/ooyala/skin-config/pull/145
=> used controlbar height from skin.json

js/components/controlBar.js, js/controller.js
See also:
https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/88/overview
Pull request in mjolnir for this same issue
=> [PBW-5352] Fixes setting pp.setTargetBitrate(ID) through console

tests/components/closedCaptionPanel-test.js, tests/components/thumbnail-carousel-test.js, tests/views/startScreen-test.js
* Added comments to thumbnails carousel test
* Fixed warnings from a start screen and closed captions tests
=> [PBW-5131] Cleanup of unit tests

js/components/closed-caption/captionOpacityTab.js, js/components/closed-caption/colorSelectionTab.js, js/components/closed-caption/fontSizeTab.js, js/components/closed-caption/fontTypeTab.js, js/components/closed-caption/languageTab.js, js/components/closed-caption/textEnhancementsTab.js, js/components/textTrackPanel.js, js/controller.js, js/skin.js, tests/components/closedCaptionPanel-test.js
⚠️  must merge with:
* https://github.com/ooyala/skin-config/pull/146
* https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/98/overview
=> [PBW-4594] Save user settings to local storage

js/controller.js
Also, tested on the devices on which this manifested earlier and are not reproducible further.
=> [PBW-5528]Discovery Up next appears fix after starting video playback

js/components/utils.js
Fixed initial value of selectedPositon
=> [PBW-5653] [V4] [Thumbnail Scrubbing] First thumbnail scrubbing images are appearing again if we scrub near the end of video

scss/responsive/_xsmall.scss
When the ad is minimized and reopen it from the recent tab, the play icon is working on android device.
Also, tested on ios device(iphone 6s) it did work.
=> [PBW-5552] play icon is working on android device

js/components/controlBar.js, js/controller.js
See matching pull requests that will be in mjolnir and html5-video-plugins.
=> [PBF-665] Adds awareness of live-button click to events.

js/components/utils.js, js/constants/constants.js, js/controller.js, scss/base/_variables.scss, scss/components/_ad-panel.scss, scss/components/_ad-screen.scss, scss/components/_closed-captions.scss, scss/components/_control-bar.scss, scss/components/_discovery-panel.scss, scss/components/_plugins.scss, scss/components/_scrollbar.scss, scss/components/_scrubber-bar.scss, scss/components/_start-screen.scss, scss/skin/_default.scss
lower skin z-index if Chrome auto-pauses flash content
=> Chrome auto-pause flash 

js/components/accessibilityControls.js, js/components/countDownClock.js, js/components/scrubberBar.js, js/components/utils.js, js/controller.js, js/skin.js, package.json, sample.html, tests/components/accessibilityControls-test.js, tests/components/controlBar-test.js, tests/components/scrubberBar-test.js, tests/components/upNextPanel-test.js, tests/components/utils-test.js, tests/controller-test.js, tests/mixins/resizeMixin-test.js, tests/skin-test.js, tests/views/adScreen-test.js, tests/views/contentScreen-test.js, tests/views/playingScreen-test.js
we should be around `88%` coverage w/ this update
=> More Unit Tests

scss/mixins/_mixins.scss, scss/skin/_default.scss
=> [PBW-5796] apply firefox fix to firefox only

js/controller.js
Added closed captions info validation that @pilievOoyala suggested
=> [PBW-5864] - Update

js/components/discoverItem.js, js/components/upNextPanel.js, js/components/utils.js, tests/components/utils-test.js
* also moved createMarkup() function to Utils for reuse on discovery and up next
=> [PBW-5739] render html on Up Next panel

js/controller.js
fixes blurred ads after clicking on upNext or Discovery element
=> [PBW-6068] removing blur when upNext or Discovery element is clicked

scss/skin/_default.scss
fixes blur not applied to flash videos
=> changing blur to apply to all kind of videos

js/components/watermark.js, js/constants/constants.js, js/views/contentScreen.js, js/views/endScreen.js, js/views/pauseScreen.js, js/views/playingScreen.js, js/views/startScreen.js, scss/base/_variables.scss, scss/components/_control-bar.scss, scss/components/_state-screen.scss, scss/components/_up-next-panel.scss, scss/components/_watermark.scss, scss/html5-skin.scss, scss/responsive/_xsmall.scss, scss/skin/_default.scss, tests/components/watermark-test.js
should work with https://github.com/ooyala/skin-config/pull/156
to test: https://goo.gl/svljJF
=> [PBW-5939] watermark related changes 

js/controller.js
- Set main video duration onAdsPlayed
- Update default value of mainVideoPlayhead
=> [PLAYER-42]

js/components/adPanel.js, tests/components/adPanel-test.js
should work with https://github.com/ooyala/skin-config/pull/157
=> [PLAYER-13] adding showAdCountDown parameter to show/hide remaining time for ads

js/views/endScreen.js, tests/views/endScreen-test.js
should work with https://github.com/ooyala/skin-config/pull/159
=> [PLAYER-15] adding title and description to end screen

js/components/sharePanel.js, tests/components/sharePanel-test.js
should work with https://github.com/ooyala/skin-config/pull/160
=> [PLAYER-168] using showEmbedTab to show or hide the embed tab

scss/components/_spinner.scss
fixes watermark not clickable when spinner is shown.
=> [PLAYER-253] allowing clicks to pass through spinner

js/components/controlBar.js, js/components/utils.js, js/controller.js
* filter out disabled buttons (from v3 metadata)
* gracefully merge array of object and maintain sort order - used for buttons array in config JSON
=> v3 to v4 deep merge updates

js/components/controlBar.js, js/components/sharePanel.js, scss/components/_share-panel.scss, tests/components/controlBar-test.js, tests/components/sharePanel-test.js
https://jira.corp.ooyala.com/browse/PLAYER-22
merge with https://github.com/ooyala/skin-config/pull/164
=> [PLAYER-22] - Configurable social sharing buttons

js/components/discoverItem.js, js/components/thumbnail.js, js/components/thumbnailCarousel.js, js/components/upNextPanel.js, js/components/utils.js, js/views/startScreen.js, tests/components/utils-test.js
undefined live stream promo image on start screen was causing console error.
added image validation to all background images.
=> background image validation

js/controller.js, tests/controller-test.js
⚠️  must merge with - https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/174/overview
=> update skin to subscribe to external API event to change caption language

js/components/adPanel.js, js/controller.js, js/skin.js
-the ad panel will now calculate the ad countdown based on a new adVideoPlayhead/currentAdPlayhead properties
-Fixes mediaset issue 3 (not 10, branch named incorrectly)
=> [mediaset-10]

js/controller.js, scss/skin/_default.scss, tests/controller-test.js
⚠️ must be merged with - https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/186/overview
[sandbox test link](http://debug.ooyala.com/ea/index.html?ec=p3eWQ1ODE6kGcyoYZj8tNOnPwEQJKxvc&pbid=ebcd684d5516464f84b6eae21bdb1328&pcode=8yMGYyOvhG5HuuITgXl_UUwes_5e&core_player=http%3A%2F%2Fplayer.ooyala.com%2Fstatic%2Fv4%2Fsandbox%2Fanamorphic%2Fcore.js&video_plugins=http%3A%2F%2Fplayer.ooyala.com%2Fstatic%2Fv4%2Fcandidate%2Flatest%2Fvideo-plugin%2Fbit_wrapper.min.js&html5_skin=http%3A%2F%2Fplayer.ooyala.com%2Fstatic%2Fv4%2Fsandbox%2Fanamorphic%2Fskin-plugin%2Fhtml5-skin.js&skin_asset=http%3A%2F%2Fplayer.ooyala.com%2Fstatic%2Fv4%2Fsandbox%2Fanamorphic%2Fskin-plugin%2Fhtml5-skin.css&additional_plugins=http%3A%2F%2Fplayer.ooyala.com%2Fstatic%2Fv4%2Fcandidate%2Flatest%2Fother-plugin%2 …
=> use attributes from core to identify anamorphic videos

README.md
language taken from - https://facebook.github.io/react/contributing/how-to-contribute.html
=> add how to contribute section to readme

tests/controller-test.js
-added mock cleanUpEventListeners function
=> [fix-unit-test]

js/components/adPanel.js
See also: https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/201/overview
=> [PBF-781] Report ad title to ad screen.

js/controller.js
-fixed an issue where IMA overlays were made transparent
=> [player-395b]

js/components/accessibilityControls.js, js/components/controlBar.js, js/components/moreOptionsPanel.js, js/components/utils.js, js/constants/constants.js, js/controller.js, js/views/endScreen.js, js/views/startScreen.js, scss/components/_buttons.scss, scss/components/_control-bar.scss, scss/components/_state-screen.scss, scss/mixins/_mixins.scss, scss/skin/_default.scss, tests/components/controlBar-test.js, tests/components/utils-test.js
[Ticket](https://jira.corp.ooyala.com/browse/PLAYER-1016)
Partial accessibility support which includes:
- Keyboard navigation for the big play button and a subset of the control bar buttons.
- ARIA labels for these same buttons
=> [PLAYER-1016] Basic accessibility support

js/constants/constants.js, js/controller.js, tests/controller-test.js
Same as this one, had the wrong branch:
https://github.com/ooyala/html5-skin/pull/764
=> [PLAYER-1257] Perceived Player Performance: Disabling loading spinner during player load

js/components/controlBar.js, js/views/endScreen.js, js/views/pauseScreen.js, js/views/playingScreen.js, scss/components/_control-bar.scss, scss/components/_pause-screen.scss, scss/components/_state-screen.scss, scss/mixins/_mixins.scss, tests/views/playingScreen-test.js
[https://jira.corp.ooyala.com/browse/PLAYER-1359](https://jira.corp.ooyala.com/browse/PLAYER-1359)
=> [PLAYER-1359]

js/components/controlBar.js
Solution to the PLAYER-1389 ticket.
=> PLAYER-1389 - prevent stuck on hover styles on mobile devices

js/components/controlBar.js, js/components/tooltip.js, js/constants/constants.js, scss/components/_control-bar.scss
To enable the tooltips please add the following property to the controlBar object.
```
"tooltips":{
"enabled":false
}
```
or use the skin.json in this PR: https://github.com/ooyala/skin-config/pull/173
=> adding tooltips for controlBar items

js/controller.js, tests/controller-test.js
=> Revert "Player 711"

js/constants/constants.js, js/controller.js
@aeng7 I made changes as per your review comments. Please check it out.
=> review comment #2 - avoiding constants in html-common

js/mixins/responsiveManagerMixin.js
-fixed an issue where subpixel sizes could fall outside of our responsive boundaries
=> [pbw-6842]

package.json
-updated deepmerge version dependency to avoid conflicts with requirejs
-recreated https://github.com/ooyala/html5-skin/pull/759
=> [PBW-6804]

tests/components/accessibilityControls-test.js, tests/components/closeButton-test.js, tests/components/controlBar-test.js, tests/components/utils-test.js, tests/components/videoQualityPanel-test.js, tests/views/contentScreen-test.js, tests/views/popover-test.js
**Please review/merge after https://github.com/ooyala/html5-skin/pull/870**
=> [PLAYER-1679b] Unit tests for quality menu accessibility feature

js/controller.js
=> [PLAYER-1270] Fix for uncaught exception when attempting to set playhead before skin

js/constants/constants.js, js/controller.js, tests/html5skin-test.js
This fixes the last issue on the [ticket](https://jira.corp.ooyala.com/browse/PLAYER-711)
=> [PLAYER-711] Setting closed captions language to none now mimics off switch behavior

js/components/unmuteIcon.js, js/constants/constants.js, js/controller.js, js/views/adScreen.js, js/views/playingScreen.js, package.json, scss/base/_variables.scss, scss/components/_unmute.scss, tests/components/unmuteIcon-test.js, tests/views/adScreen-test.js, tests/views/playingScreen-test.js
=> Player 1788b

js/components/controlBar.js, tests/components/controlBar-test.js
-fixed an issue where the volume icon and aria labels were not showing the volumeOff icon when volume was set to 0
=> [player-2063]

js/components/controlBar.js, scss/components/_unmute.scss, tests/components/controlBar-test.js
Also took the opportunity to fix the gray shadow on the un-mute button.
=> [PLAYER-2120] Fix for quality menu getting keyboard focus sometimes when using mouse

js/controller.js, tests/html5skin-test.js
-fixed an issue where muting/unmuting via skin was not notifying all plugins to do so
-improved unit tests on this
=> [player-2086]

scss/components/_unmute.scss
-updating unmute icon to be ~25% smaller. Some unmute icon positioning changes. Removed bold text
=> [player-2225]

js/components/closed-caption/fontSizeTab.js, js/components/closed-caption/selectionContainer.js, js/components/closed-caption/textEnhancementsTab.js, js/components/colorSelector.js, js/components/controlBar.js, js/components/slider.js, js/components/tooltip.js, js/views/playingScreen.js, js/views/popover.js, scss/components/_tabs.scss, tests/components/accessibleButton-test.js, tests/components/closed-caption/closedCaptionPopover-test.js, tests/components/closed-caption/fontSizeTab-test.js, tests/components/closed-caption/selectionContainer-test.js, tests/components/closed-caption/textEnhancementsTab-test.js, tests/components/colorSelector-test.js, tests/components/controlBar-test.js, tests/components/dataSelector-test.js, tests/components/higher-order/accessibleMenu-test.js, tests/components/slider-test.js, tests/components/tabs-test.js
Apart from the unit tests, this PR also includes:
- Fixed a few React warnings
- Switched the remaining control bar buttons to `AccessibleButton`'s.
=> [PLAYER-1678] Added remaining unit tests

js/components/controlBar.js, js/controller.js, js/views/playingScreen.js, scss/base/_variables.scss, scss/components/_state-screen.scss, scss/components/_up-next-panel.scss, scss/components/_vr-controls.scss, scss/components/_watermark.scss
=> Revert "Feature/player 1350"

scss/base/_variables.scss, scss/components/_watermark.scss
=> Revert "[bugfix/PBW-6987] Player 4.19.3 - watermark logo not clickable anymore"

js/components/sharePanel.js, js/constants/constants.js, scss/components/_share-panel.scss, tests/components/sharePanel-test.js
-removed the “Invest in Social Change” title for the share panel
=> [player-2078]

js/components/volumeControls.js, tests/components/volumeControls-test.js
-fixed an issue where mobile volume bars do not reflect the muted state properly
=> [player-2274]

js/controller.js, tests/html5skin-test.js
-fixed an issue where if content aspect ratio is published during an ad, the ad aspect ratio will change to that of the reported content aspect ratio
=> [player-2427]

js/controller.js, tests/html5skin-test.js
-we will now show the ad control bar if the ad gets paused so that the user has an indication to unpause the ad
=> [player-2812]

js/controller.js, js/views/pauseScreen.js, tests/html5skin-test.js, tests/views/pauseScreen-test.js
-pause screen will no longer blur video and show an opaque overlay when there is no title and no description
=> [player-2502]

js/controller.js
Listeners for MULTI_AUDIO_FETCHED event are added, function onMultiAudioFetched is empty now. No unit tests while the function is empty.
=> Feature/player-2956 Create functions for sending the info from plugins to core

js/controller.js, tests/html5skin-test.js
Add flag ("showMultiAudioIcon") that disables multi-audio functionality to avoid confusions fromusers while this part is not fully ready.
=> [featture/PLAYER-3068] Add flag to disable multi-audio

js/components/close-caption-multi-audio-menu/closeCaptionMultiAudioMenu.js
_getCloseCaptions -> _getClosedCaptions
=> [feature/PLAYER-542]: Closed

js/components/closed-caption-multi-audio-menu/tab.js, js/components/moreOptionsPanel.js, scss/components/_cc-ma-menu.scss, tests/components/moreOptionsPanel-test.js
Missed letter "N" was added in "responsive",
MultiAudio was added to moreOptionsPanel,
custom scroll (react-scrollarea) was added for multi-audio-and-cc popover
Config branch is "feature/multi-audio-more-options"
=> Feature/multi-audio-more-options to dev-epam

.eslintrc, package.json, scripts/git/pre-commit, scripts/hooks/pre-commit
This PR introduces a new feature - ESLint(Linting utility for js and jsx). It's not in any case a single source of truth, it's just and attempt to start a discussion. Some of the rules are taken from the styleguide, some are just recommended and community-wide adopted best practices. We could add more rules as we progress.
ESLint is an awesome tool that could allow us enforce code style rules, reduce the number of code style comments in PR and help us write better code overall. It has integrations with pretty much every editor and is really easy to setup and use.
The purpose of this PR is to introduce the feature, essentially it does not affect any aspect of the development at this point, but it might be used later at the build stage, CI, etc.
ESLint can be installed both globally and …
=> Add ESLint and ESLint run command in package.json

js/components/closed-caption-multi-audio-menu/helpers.js, js/components/closed-caption-multi-audio-menu/multiAudioTab.js, tests/components/closed-caption-multi-audio-menu/helpers-test.js, tests/components/closed-caption-multi-audio-menu/multiAudioTab-test.js
Rework multi audio language labels.
Basically we had to reimplement label assignment based on new acceptance criteria.
- [PLAYER-3147](https://jira.corp.ooyala.com:8443/browse/PLAYER-3147)
- All unit tests passed
- Covered all acceptance criteria from [PLAYER-3147](https://jira.corp.ooyala.com:8443/browse/PLAYER-3147) description and corner cases
=> [feature/PLAYER-3147] implement new label functionality

js/controller.js, tests/html5skin-test.js
Set state multiAudio to null when embed code was changed.
Origin task is https://jira.corp.ooyala.com/browse/PLAYER-3310
=> Feature/player 3310 Issue with playlist when switching from video with multi audio to one with only a single track

.eslintrc, js/controller.js
This fixes remaining ESLint errors in controller.
=> controller eslint

js/components/closed-caption-multi-audio-menu/closedCaptionMultiAudioMenu.js, js/components/controlBar.js, js/controller.js, js/views/contentScreen.js, tests/components/controlBar-test.js, tests/html5skin-test.js
We do not pause a video after opening multiAudio screen.
Task is https://jira.corp.ooyala.com/browse/PLAYER-3333
=> Bugfix/player 3333 Pausing of live playback while changing language in minimized screen

js/components/closed-caption-multi-audio-menu/closedCaptionMultiAudioMenu.js, js/components/closed-caption-multi-audio-menu/helpers.js, js/components/closed-caption-multi-audio-menu/multiAudioTab.js, tests/components/closed-caption-multi-audio-menu/helpers-test.js, tests/components/closed-caption-multi-audio-menu/multiAudioTab-test.js
According the ticket https://jira.corp.ooyala.com/browse/PLAYER-3375 custom labels (such as "Undefined language" and "No inguistic content") should be localized. We have translations for the values in languages files.
=> [feature/PLAYER-3375] Localization for "Undefined language" and "No inguistic content"

scss/components/_plugins.scss
-fixed an issue where the plugins div could support variable heights for ads
=> [player-3531]

js/controller.js, tests/html5skin-test.js
-SET_CURRENT_AUDIO will now be published with the current video id
=> [player-3811]

README.md
-updating readme to reference Node version 8.11.3
=> [update-readme-with-new-node]

js/controller.js, tests/html5skin-test.js
=> [PLAYER-3831][v4] [VAST] [Ad countdown] - Ad countdown is stuck at 0

js/components/controlButton.js, js/components/higher-order/preserveKeyboardFocus.js, js/components/skipControls.js, js/components/utils.js, js/skin.js, js/views/pauseScreen.js, js/views/playingScreen.js, tests/components/controlBar-test.js, tests/components/higher-order/preserveKeyboardFocus-test.js, tests/components/utils-test.js, tests/skin-test.js
This update contains fixes for the above ticket numbers and also the following changes:
- New unit tests. These are not related to the fixes. I'm still working on finishing the unit tests for Skip Controls in general, so I'll add more in a future PR.
- Fixed a lot of warnings that are shown when running unit tests.
- Updated `PreserveKeyboardFocus` component in order to use latest React patterns
=>  [PLAYER-3886][PLAYER-3872][PLAYER-3856] Various fixes and unit tests

js/components/controlButton.js, js/components/higher-order/holdOnClick.js, js/components/higher-order/preserveKeyboardFocus.js, js/components/skipControls.js, js/components/tooltip.js, js/controller.js, tests/components/accessibilityControls-test.js, tests/components/controlBar-test.js, tests/components/controlButton-test.js, tests/components/higher-order/holdOnClick-test.js, tests/components/higher-order/preserveKeyboardFocus-test.js, tests/components/scrubberBar-test.js, tests/components/skipControls-test.js, tests/components/thumbnail-carousel-test.js, tests/skin-test.js, tests/views/endScreen-test.js, tests/views/pauseScreen-test.js, tests/views/playingScreen-test.js
Included in this PR:
- Added unit tests for Skip Controls
- Fixed all remaining warnings that used to show up when running unit tests
- Updated new Skip Control-related components in order to use newer React patterns
=> [PLAYER-3475] Unit tests for Skip Controls feature

js/controller.js, tests/html5skin-test.js
There is no unit test because of errors when trying to render the DOM in the unit test environment.
=> Player 3519

js/components/controlBar.js, tests/components/controlBar-test.js
Hide volume icon if platform is Ios.
Origin task is https://jira.corp.ooyala.com/browse/PLAYER-3877
=> [bf/PLAYER-3877] hide volume icon if platform is Ios

.gitmodules, js/components/closed-caption-multi-audio-menu/closedCaptionMultiAudioMenu.js, js/components/closed-caption-multi-audio-menu/multiAudioTab.js, js/controller.js, tests/components/closed-caption-multi-audio-menu/helpers-test.js, tests/components/closed-caption-multi-audio-menu/multiAudioTab-test.js, tests/html5skin-test.js
- html5-common is so big to be included as submodule to the repo. So html5-common was removed.
- param with languageList was added to params of MULTI_AUDIO_FETCHED
+ Some changes in controller.js for eslint 
Сonjugate PR: https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/518/overview
=> Feature/player 3993 pass languageList as param

js/controller.js, tests/html5skin-test.js
-fixed an issue where an ad resumes playback immediately after a clickthrough
-cleaned up usage of plugins elements in html5skin-test.js
=> Player 4041

js/components/menuPanel.js, js/components/menuPanelItem.js, js/components/playbackSpeedButton.js, js/components/utils.js, tests/components/controlBar-test.js, tests/components/customScrollArea-test.js, tests/components/menuPanel-test.js, tests/components/menuPanelItem-test.js, tests/components/moreOptionsPanel-test.js, tests/components/playbackSpeedButton-test.js, tests/components/playbackSpeedPanel-test.js, tests/components/utils-test.js, tests/html5skin-test.js, tests/skin-test.js
This contains all the unit tests for the Playback Speed UI feature and some minor fixes.
=> [PLAYER-3645] Unit tests for Playback Speed UI

js/views/audioOnlyScreen.js
=> [fix-unit-tests]

tests/components/utils-test.js
-submodule update for the default audio only option to be false
=> [update-submodule] - Audio Only Default to false

js/components/discoveryPanel.js, js/skin.js, tests/skin-test.js
=> [bugfix/PLAYER-4485] JS Player uses id on markup

js/components/controlBar.js, js/controller.js, scss/components/_control-bar.scss, tests/components/controlBar-test.js, tests/html5skin-test.js, tests/skin-test.js, tests/views/audioOnlyScreen-test.js, tests/views/endScreen-test.js, tests/views/pauseScreen-test.js, tests/views/playingScreen-test.js
This branch contains the implementation of the Cast SDK button that handles the interaction of the sender and the receiver.  
Also removes the custom button used to manage the cast action from sender to receiver
=> [PLAYER-4508] Replace custom cast button

js/controller.js
Gulp build compatibility returned
=> Hotfix: gulp build compatibility returned

js/components/controlBar.js, scss/components/_control-bar.scss, tests/components/controlBar-test.js
https://jira.corp.ooyala.com/browse/PLAYER-4584
Added oo-flex-end css class for justify-content: flex-end.
=> Bugfix - PLAYER-4584

js/components/castPanel.js, js/components/utils.js, js/constants/constants.js, js/views/endScreen.js, js/views/pauseScreen.js, js/views/playingScreen.js, tests/components/castPanel-test.js
Fixed linting errors;
Implemented localization into CastPanel component
=> fix/PLAYER-4755 lint errors fixed; CastPanel localization implemented

js/controller.js
Changed options of DeepMerge inside loadConfigData for mergedMetaData (need to prepend playbackSpeed button)
https://jira.corp.ooyala.com/browse/PLAYER-4675
=> bugfix - PLAYER-4675

js/controller.js, npm-shrinkwrap.json, package.json
Added polyfills for Android 4.4.4 browsers
https://jira.corp.ooyala.com/browse/PBW-7501
=> Added Polyfill

js/controller.js, tests/html5skin-test.js
https://jira.corp.ooyala.com/browse/PLAYER-4136
Unit tests passed
=> Added 'fluid' option for aspectRation configuration

js/components/controlBar.js, js/components/playbackSpeedPanel.js
Changes to use backlot settings in audio player.
Jira ticket: https://jira.corp.ooyala.com/browse/PLAYER-4678
=> [PLAYER-4678]- Issue with settings in backlot, none of the settings work for Audio only player

js/controller.js
Fixed the logic of fluid.
https://jira.corp.ooyala.com/browse/PLAYER-4136
=> Fix for PLAYER-4136 "fluid" to aspectRatio

js/components/countDownClock.js, js/components/discoveryPanel.js, js/components/upNextPanel.js, js/components/utils.js, js/constants/constants.js, js/controller.js, tests/components/discoveryPanel-test.js, tests/components/utils-test.js, tests/controller-test.js
Required to report discovery analytics with the JSON pipeline
=> Player 590 2

js/components/controlBar.js, js/components/playbackSpeedPanel.js
@ipadilla4 we need to move to candidate. Reverted your changes, since it broke 12 tests.
This reverts commit 5c2237a924ee759fa7a9749b14808084f197671a.
=> Revert "Changes to use backlot settings in audio player"

js/components/controlBar.js, js/components/playbackSpeedPanel.js, tests/components/controlBar-test.js
Changes to use backlot settings in audio player and some test modifications.
=> [PLAYER-4678] - Issue with settings in backlot, none of the settings work for Audio only player

js/controller.js
[core fix link](https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/615/overview)
Evaluate scope to enable the following Player API:
* Add an API to disable/enable CC
* Add an API to retrieve the current CC settings (enabled/disabled, language, etc.)
* We can disable CC by calling setClosedCaptionsLanguage('none') but we cannot re-enable it afterwards
https://jira.corp.ooyala.com/browse/PLAYER-4888
=> [PLAYER-4888] Enable/disable CC via JavaScript API

js/controller.js
When skin receives error from mjolnir it doesn't stop the audio.
I appreciate if someone would comment this solution.
=> [PLAYER-4881] pause on getting error

js/controller.js
Reverts ooyala/html5-skin#1194
=> Revert "[PLAYER-4888] Enable/disable CC via JavaScript API"

js/components/utils.js, tests/components/utils-test.js, tests/html5skin-test.js
Revert changes from [PR](https://github.com/ooyala/html5-skin/pull/1193)
=> [revert/PLAYER-4606] revert changes for a task PLAYER-4606

js/components/closed-caption/languageTab.js, js/components/closed-caption/onOffSwitch.js, js/controller.js, tests/components/closedCaptionPanel-test.js, tests/html5skin-test.js
* [PLAYER-4888](https://jira.corp.ooyala.com/browse/PLAYER-4888) Enable/disable CC via JavaScript API
* [PLAYER-4887](https://jira.corp.ooyala.com/browse/PLAYER-4887) Enabling setting Closed Captions when casting
additional changes for [this PR](https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/620/overview)
includes reverted changes from 4888
=> Player 4887

js/views/adScreen.js, js/views/pauseScreen.js, tests/views/adScreen-test.js
Add Spinner and to Ad Screen if buffering time is 0.
=> [bf/PBW-7731] add Spinner to ad screen

js/components/controlBar.js
https://jira.corp.ooyala.com/browse/PLAYER-5150
=> [fix/PLAYER-5150] Not able to access the airplay option using tab

iframe.html
Reverts ooyala/html5-skin#1184
=> Revert "Fixed iframe playerParams parsing (enhanced for inline skin)"

js/controller.js
https://jira.corp.ooyala.com/browse/PLAYER-5095
=> [fix/PLAYER-5095] casting on apple tv via airplay stops on reloading

js/constants/constants.js, js/controller.js, webpack.config.js
https://jira.corp.ooyala.com/browse/PLAYER-5165
=> [fix/PLAYER-5165] Airplay icon is not displayed as expected on refresh/reload

js/controller.js
Add page-level parameter to disable AirPlay option
https://jira.corp.ooyala.com/browse/PLAYER-5204
=> [feature/PLAYER-5204] Add page-level parameter to disable AirPlay

js/constants/constants.js, js/controller.js, js/views/audioOnlyScreen.js, scss/components/_state-screen.scss, scss/skin/_default.scss
https://jira.corp.ooyala.com/browse/PLAYER-4194
=> [fix/PLAYER-4194] Poster for Audio-only

Jenkinsfile
=> Player 5061

Jenkinsfile
=> Change Jenkinsfile

sonar-project.properties
=> Add sonar-project.properties

js/components/controlBar.jsx, js/controller.js, tests/components/controlBar-test.js, tests/html5skin-test.js
https://jira.corp.ooyala.com/browse/PLAYER-5209
=> [fix/PLAYER-5209] Only enable Discovery button if Discovery is enabled

iframe.html
attribute title was added as default with value "ooyala-player"
=> [bugfix/PLAYER-5004]  Add "title" attribute to iframe

js/controller.js
https://jira.corp.ooyala.com/browse/PLAYER-5204
=> [fix/PLAYER-5204] Add page-level parameter to disable AirPlay option

iframe.html, js/components/accessibleButton.jsx, js/components/controlButton.jsx, js/components/directionControlVr.jsx, js/components/viewControlsVr.jsx, js/constants/constants.js, scss/components/_cc-ma-menu.scss, scss/components/_control-bar.scss, scss/components/_menu-panel.scss, scss/components/_more-options.scss, scss/components/_vr-controls.scss, scss/mixins/_mixins.scss, tests/components/directionControlVr-test.js, tests/components/viewControlsVr-test.js
Accessibility for navigation buttons for video 360  was added.
[Related PR](https://github.com/ooyala/skin-config/pull/233)
=> bugfix/PLAYER-5121 Improve 360 video accessibility

js/components/controlBar.jsx, js/controller.js, tests/components/controlBar-test.js, tests/html5skin-test.js
[Core PR](https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/648/overview)
=> [PLAYER-5311] Move airplay init logic to the core

js/components/scrubberBar.jsx
This branch allow the seek action on the scrubber bar along with markers.
=> [PLAYER-5374] Fix to get position of marker at seek

js/controller.js
Fix error on OSP trying to access metadata information
This also fixes PLAYER-5381 (Issue when video is paused, for both live and VOD assets)
=> [PLAYER-5380] Issue with end screen

js/components/markers/markerIcon.jsx, tests/components/markers/markerIcon-test.js
Added the needed code to update the playhead once the marker gets clicked.
=> [PLAYER-5375] Update playhead on marker clicked at pause screen

Jenkinsfile
=> [PLAYER-5061] Change repositoryKey

js/skin.jsx
This will fix the interaction with the player using the Tab key at fullscreen.
=> [PBW-8049] Tab focus not working on Fullscreen

js/components/accessibleButton.jsx, js/components/closeButton.jsx, js/components/controlBar.jsx, js/components/icon.jsx, js/components/scrubberBar.jsx, js/components/textTrackPanel.jsx, js/controller.js, js/views/contentScreen.jsx, js/views/pauseScreen.jsx, js/views/playingScreen.jsx, js/views/popover.jsx, scss/components/_closed-captions.scss, scss/components/_content-screen.scss, scss/components/_popover.scss, scss/components/_state-screen.scss, scss/components/_text-track.scss, scss/components/_volume-controls.scss, scss/responsive/_xsmall.scss
As discovered in the PBW-8120 when <HTML dir="rtl"> attribute appeared the skin shown closed captions with shift. After my investigations several issues more found:
- Icon "play" was invalid
- Scrubber bar playhead marker moved from left to right
- ClosedCaptions popup markup got broken
- ClosedCaptions tuning screen got broken as well among with `close` button
Fixed it all.
=> [PBW-8120] styles and skin adopted for RTL mode

js/constants/constants.js
corresponding pr in mjolnir: https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/693/overview
=> [PLAYER-4174] add missing error message

js/components/controlBar.jsx, tests/components/__snapshots__/utils-test.js.snap
It's a tiny fix to achieve proper accessibility figure.
=> [PBW-8050] changed role of Play and Mute button from `radio` to `switch`

amp_iframe.html
Adding IMA plugin to amp iframe
=> [PBW-45503] AMP-Ooyala implementation does not shows IMA ads.
